default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: iterable_dev

test:
  <<: *default
  database: iterable_test

# production:
#   <<: *default
#   database: iterable_prod
